version: "3.8"
services:
  api:
    build: ./api
    container_name: api_c
    ports:
      - 4000:4000
    volumes:
      - ./api:/myapi
      - /myapi/node_modules
  myblog:
    build: ./vue-app
    container_name: myblog_c
    ports:
      - 8080:8080
    volumes:
      - ./vue-app:/app
      - /app/node_modules